buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath group: 'net.minecraftforge.gradle', name: 'ForgeGradle', version: '6.0.+', changing: true
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'maven-publish'

group = 'com.dominhquan'
version = '1.0.0'

base {
    archivesName = 'dominhquansword'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                dominhquansword {
                    source sourceSets.main
                }
            }
        }
        client {}
        server {}
    }
}

repositories {
    mavenCentral()
    maven {
        name = 'minecraftforge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'mojang'
        url = 'https://libraries.minecraft.net/'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': 'dominhquansword',
            'Specification-Vendor': 'Do Minh Quan',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version,
            'Implementation-Vendor': 'Do Minh Quan'
        ])
    }
}

jar.finalizedBy('reobfJar')
