pluginManagement {
    repositories {
        maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven { name = 'Forge'; url = 'https://maven.minecraftforge.net/' }
    }
}
rootProject.name = 'dominhquansword'
